# Generated by Django 5.2.7 on 2025-10-07 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created this specification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='spec',
            index=models.Index(fields=['user', '-created_at'], name='specs_spec_user_id_2ed2e1_idx'),
        ),
    ]
